---
- name: Fetch users List from Ansible Tower
  hosts: 16.170.124.220
  gather_facts: false
  tasks:
    - name: Execute windowsaccount.ps1 file
      script: windowsaccount.ps1
      register: script_result
      args:
        executable: powershell.exe

    - debug:
        var: script_result.stdout_lines
    - debug:
        var: script_result.stderr
    - set_fact:
        script_result: "{{ script_result.stdout_lines }}"
        
    - name: Run SQL*Plus to insert data into Oracle table
      delegate_to: localhost
      shell: |
        sqlplus -S "{{ oracle_username }}/{{ oracle_password }}"@{{ hostname }}:{{ port }}/{{ servicename }} <<EOF
        INSERT INTO SYSTEM_INFO (SERVER, USERNAME)
        VALUES ('{{ script_result }}', '{{ script_result.stdout_lines }}');
        COMMIT;
        EXIT;
        EOF
      register: sql_output
