---
- name: Fetch users List from Ansible Tower
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Execute windowsaccount.ps1 file
      script: windowsaccount.ps1
      register: script_result
      args:
        executable: powershell.exe

    - debug:
        var: script_result.stdout_lines
    - debug:
        var: script_result.stderr
    - set_fact:
        script_result: "{{ script_result.stdout_lines }}"
